DROP SCHEMA IF EXISTS projectdb CASCADE;
CREATE SCHEMA projectdb;

DROP TABLE IF EXISTS projectdb.licenseinfo;
CREATE TABLE projectdb.licenseinfo(
	LICENSE_SERIAL_NUMBER INT NOT NULL,
	LICENSE_TYPE_CODE VARCHAR(50) NOT NULL,
	LICENSE_CLASS_CODE VARCHAR(50) NOT NULL,
	CERTIFICATE_NUMBER BIGINT NOT NULL,
	PREMISE_NAME VARCHAR(255),
	PRIMARY KEY(LICENSE_SERIAL_NUMBER)
);


DROP TABLE IF EXISTS projectdb.locationinfo;
CREATE TABLE projectdb.locationinfo(
	LOCATION_ID INT GENERATED ALWAYS AS IDENTITY,
	LICENSE_SERIAL_NUMBER INT NOT NULL,
	COUNTY VARCHAR(50) NOT NULL,
	PREMISE_NAME VARCHAR(255),
	PREMISE_ADDR TEXT ,
	CITY_NAME VARCHAR(120) NOT NULL,
	STATE_NAME VARCHAR(120) NOT NULL,
	ZIP VARCHAR(120),
	GEO_POINT VARCHAR(120) NOT NULL,
	ZONE_NAME VARCHAR(50),
	PRIMARY KEY(LOCATION_ID),
	CONSTRAINT fk_serial
		FOREIGN KEY(LICENSE_SERIAL_NUMBER)
			REFERENCES projectdb.licenseinfo(LICENSE_SERIAL_NUMBER)
			ON DELETE SET NULL
);

DROP TABLE IF EXISTS projectdb.dateinfo;
CREATE TABLE projectdb.dateinfo(
	LICENSE_SERIAL_NUMBER INT NOT NULL,
	LICENSE_ISSUED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	LICENSE_EXPIRY_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	RECENT_STARTDATE_LICENSE DATE,
	ORIGINAL_DATE DATE,
	CONSTRAINT fk_serial
		FOREIGN KEY(LICENSE_SERIAL_NUMBER)
			REFERENCES projectdb.licenseinfo(LICENSE_SERIAL_NUMBER)
			ON DELETE SET NULL
);

DROP TABLE IF EXISTS projectdb.operationinfo;
CREATE TABLE projectdb.operationinfo(
	OPERATION_INFO_ID INT GENERATED ALWAYS AS IDENTITY,
	LICENSE_SERIAL_NUMBER INT NOT NULL,
	INFO_DESC VARCHAR(255),
	METHOD_OF_OPERATION VARCHAR(255) DEFAULT 'NOT ASSIGNED',
	DBA VARCHAR(255),
	OTHER_INFO TEXT DEFAULT 'NO INFO',
	PRIMARY KEY(OPERATION_INFO_ID),
	CONSTRAINT fk_serial
		FOREIGN KEY(LICENSE_SERIAL_NUMBER)
			REFERENCES projectdb.licenseinfo(LICENSE_SERIAL_NUMBER)
			ON DELETE SET NULL
);

DROP TABLE IF EXISTS projectdb.userinfo;
CREATE TABLE projectdb.userinfo(
	USER_NAME VARCHAR(255) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	ACCESS_TYPE VARCHAR(25) NOT NULL DEFAULT 'NON_ADMIN',
	PRIMARY KEY(USER_NAME)
	
);

DROP TABLE IF EXISTS projectdb.userlog;
CREATE TABLE projectdb.userlog(
	USER_ID INT GENERATED ALWAYS AS IDENTITY,
	USER_NAME VARCHAR(255) NOT NULL,
	SEARCH_DATE DATE DEFAULT CURRENT_DATE,
	SEARCH_HISTORY VARCHAR(512),
	LOG_INFO VARCHAR(512),
	OTHER VARCHAR(512),
	PRIMARY KEY(USER_ID),
	CONSTRAINT fk_serial
		FOREIGN KEY(USER_NAME)
			REFERENCES projectdb.userinfo(USER_NAME)
			ON DELETE SET NULL
);

